name: app_prodem_v1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  nb_utils: ^7.1.6
  flutter_svg: ^2.2.0
  provider: ^6.1.4
  carousel_slider: ^5.1.1
  #screen
  image_picker: ^1.1.2
  qr_code_tools: ^0.2.0
  mobile_scanner: ^7.0.1
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  auto_route: ^10.1.2
  dotenv: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/img/
