import '../entities/entity.dart';

abstract class SaveOnlineThirdDepositRepository {
  Future<SaveOnlineThirdDepositResponseEntity> saveOnlineThirdDeposit(
    String accountDestiny,
    String accountOrigin,
    String ammount,
    String bankOrigin,
    String customerDepositName,
    String depositDate,
    String depositVoucher,
    String destinyOfFunds,
    String idBankOrigin,
    String idMoney,
    String idPerson,
    String idSavingAccount,
    String idThirdOnlineDeposit,
    String idUser,
    String idWebPersonClient,
    String idWebPersonClientCreate,
    String idcOriginType,
    String idcState,
    String identityCardNumber,
    String imei,
    String ipAddress,
    String isOwnAccount,
    String location,
    String moneyCode,
    String nombreCliente,
    String observations,
    String sourceOfFunds,
    String usuarioRegistro,
    String whatsAppNumber,
    String idLoanCredit,
    String? vToken,
    String idSMSOperation,
    String prodemKeyCode,
  );
}
